CREATE TABLE
  `buyCredits` (
    `id` varchar(10) NOT NULL DEFAULT '0',
    `username` varchar(50) DEFAULT NULL,
    `email` varchar(100) DEFAULT NULL,
    `name` varchar(50) DEFAULT NULL,
    `phoneNumber` varchar(20) DEFAULT NULL,
    `birthDate` date DEFAULT NULL,
    `encryptionKey` varchar(100) DEFAULT NULL,
    `date` bigint DEFAULT NULL,
    `time` varchar(50) DEFAULT NULL,
    `currency` varchar(8) DEFAULT NULL,
    `amount` decimal(18, 8) DEFAULT NULL,
    `walletAddress` varchar(100) DEFAULT NULL,
    `credits` int DEFAULT NULL,
    `status` enum('completed', 'processing', 'failed') DEFAULT 'processing',
    `transactionId` varchar(255) DEFAULT NULL,
    `transactionHash` varchar(255) DEFAULT NULL,
    `transactionScreenshot` varchar(255) DEFAULT NULL,
    `ip` varchar(50) DEFAULT NULL,
    `userAgent` varchar(255) DEFAULT NULL,
    `orderLoggingEnabled` tinyint(1) DEFAULT NULL,
    `session_id` varchar(255) DEFAULT NULL,
    `blockExplorerLink` varchar(255) DEFAULT NULL,
    `rate` decimal(10, 3) DEFAULT NULL,
    `cryptoAmount` varchar(20) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `paymentMethod` varchar(255) DEFAULT NULL,
    `package` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `username` (`username`),
    CONSTRAINT `buyCredits_ibfk_1` FOREIGN KEY (`username`) REFERENCES `userData` (`username`) ON DELETE CASCADE
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci